#!/usr/bin/env python3
"""Convert the pictures of the original CD into KPIC files for the CDTV.

  convimg.py palette OUT.json IMG...          shared interface palette
  convimg.py pic PALETTE.json IN.BMP OUT.PIC  convert a 640x480 screen
  convimg.py atlas PALETTE.json SHEETDIR OUT.PIC   cutouts of one screen
  convimg.py crop PALETTE.json SHEET OUT.PIC BG X Y W H DX DY  a single cutout
  convimg.py drill PALETTE.json SHEETDIR OUTDIR    the drill screens
  convimg.py item IN.BMP OUT.PIC              the picture of an entry

KPIC format (big endian):
  'KPIC', UWORD width, height, bitplanes, number of colours, first colour,
  the colours (UWORDs 0x0RGB), bitplanes (plane 0 first, rows aligned to 16
  bits)

Screens and cutouts use colours 0-15 (the shared interface palette); the
entry pictures use colours 16-31 like the video clips, skipping 17-19, which
belong to the mouse pointer sprite.
"""
import argparse
import json
import struct

import numpy as np
from PIL import Image

import amigagfx as ag

SCREEN_W, SCREEN_H = 320, 256
TOP = (SCREEN_H - 240) // 2


def load_screen(path):
    """A 640x480 screen halved to 320x240 and centred on 320x256."""
    im = Image.open(path).convert('RGB')
    if im.size != (640, 480):
        raise SystemExit(f'{path}: attesa 640x480, trovata {im.size[0]}x{im.size[1]}')
    small = im.resize((SCREEN_W, 240), Image.Resampling.LANCZOS)
    canvas = Image.new('RGB', (SCREEN_W, SCREEN_H))
    canvas.paste(small, (0, TOP))
    return np.array(canvas)


def write_kpic(path, idx, pal, planes, base=0):
    h, w = idx.shape
    with open(path, 'wb') as f:
        f.write(struct.pack('>4sHHHHH', b'KPIC', w, h, planes, len(pal), base))
        f.write(struct.pack(f'>{len(pal)}H', *ag.palette_words(pal)))
        f.write(ag.planar(idx, planes))


def quantize(rgb, pal, dither='none'):
    if dither == 'fs':
        return ag.map_fs(rgb, pal)
    return ag.nearest(rgb, pal).reshape(rgb.shape[:2])


GREEN_ON = (53, 246, 4)		# the bright green of the drill boxes


def nearest_index(pal, rgb):
    return int(ag.nearest(np.array([rgb], np.uint8), pal)[0])


# pens the interface draws with: the nearest colour in the shared palette
PENS = (('BLACK', (0, 0, 0)), ('TEXT', (255, 153, 0)), ('WHITE', (255, 255, 255)),
        ('RED', (204, 34, 34)), ('GREEN', (53, 246, 4)))


def cmd_palette(args):
    pix = np.concatenate([load_screen(p).reshape(-1, 3) for p in args.images])
    # black plus the two greens of the drills: the bright one of the
    # "right"/"wrong" boxes and the dark one of the halo around the chosen
    # answer (with only the bright green the halo turns into stray pixels)
    pal = ag.make_palette(pix, args.colors,
                          fixed=[(0, 0, 0), GREEN_ON, (0, 81, 0)])
    with open(args.out, 'w') as f:
        json.dump(pal.tolist(), f)
    print(f'{args.out}: {len(pal)} colours from {len(args.images)} images')
    if args.header:
        lines = ['/* generated by tools/convimg.py: do not edit */',
                 '#ifndef KLL_PALETTE_H', '#define KLL_PALETTE_H', '']
        for name, rgb in PENS:
            i = int(ag.nearest(np.array([rgb], np.uint8), pal)[0])
            lines.append(f'#define PEN_{name}\t{i}\t/* {pal[i][0]:02X}{pal[i][1]:02X}{pal[i][2]:02X} */')
        lines += ['', '#endif']
        with open(args.header, 'w') as f:
            f.write('\n'.join(lines) + '\n')


def cmd_pic(args):
    pal = load_palette(args.palette)
    rgb = load_screen(args.src)
    idx = quantize(rgb, pal, args.dither)
    planes = max(1, (len(pal) - 1).bit_length())
    write_kpic(args.out, idx, pal, planes)
    if args.preview:
        ag.preview(idx, pal).save(args.preview)


def load_palette(path):
    with open(path) as f:
        return np.array(json.load(f), np.uint8)


_images = {}


def load_rgb(path):
    if path not in _images:
        _images[path] = Image.open(path).convert('RGB')
    return _images[path]


def crop_tile(sheet, box, dest, bg):
    """A cutout of a sheet, halved the same way the screens are.

    The cutout is first pasted onto the background screen, at the position it
    will end up in, and only the composition is halved: that way the edge
    pixels come from the same pair of pixels as the halved background, and the
    lit button lines up with the artwork around it. Halving the cutout on its
    own, as this used to do, shifts it by half a pixel and drags in the white
    that separates the cells of the sheet.
    """
    x, y, w, h = box
    dx, dy = dest
    full = load_rgb(bg).copy()
    full.paste(load_rgb(sheet).crop((x, y, x + w, y + h)), (dx, dy))
    small = full.resize((full.width // 2, full.height // 2), Image.Resampling.LANCZOS)
    w, h = (w + 1) // 2, (h + 1) // 2
    tile = np.array(small)[dy // 2:dy // 2 + h, dx // 2:dx // 2 + w]
    if tile.shape[:2] != (h, w):
        raise SystemExit(f'{sheet}: cutout {box} falls outside the screen')
    return tile


def cmd_crop(args):
    pal = load_palette(args.palette)
    rgb = crop_tile(args.sheet, (args.x, args.y, args.w, args.h),
                    (args.dx, args.dy), args.bg)
    idx = quantize(rgb, pal)
    write_kpic(args.out, idx, pal, max(1, (len(pal) - 1).bit_length()))


def cmd_atlas(args):
    """Collect the cutouts of one screen into a single image."""
    import layout

    pal = load_palette(args.palette)
    tiles, height = layout.pron_atlas() if args.which == 'pron' else layout.hol_atlas()
    canvas = np.zeros((height, SCREEN_W, 3), np.uint8)
    for t in tiles:
        rgb = crop_tile(f'{args.sheets}/{t["sheet"]}.BMP', t['crop'],
                        t['full_dest'], f'{args.sheets}/{t["bg"]}.BMP')
        x, y = t['at']
        h, w = rgb.shape[:2]
        canvas[y:y + h, x:x + w] = rgb[:height - y, :SCREEN_W - x]
    idx = quantize(canvas, pal)
    write_kpic(args.out, idx, pal, max(1, (len(pal) - 1).bit_length()))
    print(f'{args.out}: {len(tiles)} cutouts, {SCREEN_W}x{height}')


def cmd_mainovl(args):
    """Menu panels with one entry lit, one per category."""
    import layout

    pal = load_palette(args.palette)
    for name, sheet, crop, dest in layout.MAIN_CROPS:
        rgb = crop_tile(f'{args.sheets}/{sheet}.BMP', crop, dest,
                        f'{args.sheets}/{layout.MAIN_BG}.BMP')
        idx = quantize(rgb, pal)
        out = f'{args.outdir}/{name}.PIC'
        write_kpic(out, idx, pal, max(1, (len(pal) - 1).bit_length()))
    print(f'{args.outdir}: {len(layout.MAIN_CROPS)} menu panels')


def cmd_drill(args):
    """Drill screens and their lit cutouts, one set per category."""
    import layout

    pal = load_palette(args.palette)
    planes = max(1, (len(pal) - 1).bit_length())
    tiles, height = layout.drill_atlas()
    for n, (dirname, label) in enumerate(layout.CATEGORIES, 1):
        cat = f'{args.sheets}/{dirname}'
        for suffix, screen in layout.DRILL_SCREENS:
            idx = quantize(load_screen(f'{cat}/{screen}.BMP'), pal)
            write_kpic(f'{args.outdir}/D{n}{suffix}.PIC', idx, pal, planes)
        canvas = np.zeros((height, SCREEN_W, 3), np.uint8)
        soft = np.zeros((height, SCREEN_W), bool)
        for t in tiles:
            rgb = crop_tile(f'{cat}/{t["sheet"]}.BMP', t['crop'], t['full_dest'],
                            f'{cat}/{t["bg"]}.BMP')
            x, y = t['at']
            h, w = rgb.shape[:2]
            canvas[y:y + h, x:x + w] = rgb[:height - y, :SCREEN_W - x]
            if t['name'].startswith('DBOX'):
                soft[y:y + h, x:x + w] = True
        # the halo of the chosen answer uses only the dark green: the bright
        # one is left to the "right"/"wrong" boxes, where it has to stand out
        idx = quantize(canvas, pal)
        keep = [i for i in range(len(pal)) if i != nearest_index(pal, GREEN_ON)]
        dark = np.array(keep, np.uint8)[quantize(canvas, pal[keep])]
        idx = np.where(soft, dark, idx)
        write_kpic(f'{args.outdir}/D{n}H.PIC', idx, pal, planes)
    print(f'{args.outdir}: {len(layout.CATEGORIES)} sets of drill screens')


def parse_reserve(values):
    """--reserve 17=F80 -> {17: (0xFF, 0x88, 0x00)}"""
    out = {}
    for v in values or ():
        slot, rgb = v.split('=')
        n = int(rgb, 16)
        out[int(slot)] = tuple(((n >> s) & 15) * 17 for s in (8, 4, 0))
    return out


def cmd_item(args):
    """The picture of an entry: 236x156 -> halved, in colours 16-31."""
    im = Image.open(args.src).convert('RGB')
    small = im.resize((args.width, args.height), Image.Resampling.LANCZOS)
    rgb = np.array(small)

    reserved = parse_reserve(args.reserve)
    slots = [i for i in range(args.base, args.base + args.colors) if i not in reserved]
    pal = ag.make_palette(rgb.reshape(-1, 3), len(slots))
    idx = quantize(rgb, pal, args.dither)

    full = np.zeros((args.colors, 3), np.uint8)
    for j, s in enumerate(slots):
        full[s - args.base] = pal[j]
    for s, c in reserved.items():
        full[s - args.base] = c
    remap = np.array([slots[j] for j in range(len(slots))], np.uint8)
    write_kpic(args.out, remap[idx], full, 5, base=args.base)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest='cmd', required=True)

    p = sub.add_parser('palette', help='compute the shared palette')
    p.add_argument('out')
    p.add_argument('images', nargs='+')
    p.add_argument('--colors', type=int, default=16)
    p.add_argument('--header', help='also write the pens for the C code')
    p.set_defaults(func=cmd_palette)

    p = sub.add_parser('pic', help='convert a screen to KPIC')
    p.add_argument('palette')
    p.add_argument('src')
    p.add_argument('out')
    p.add_argument('--dither', choices=('none', 'fs'), default='none',
                   help='no dithering, or Floyd-Steinberg')
    p.add_argument('--preview', help='also save a PNG to look at')
    p.set_defaults(func=cmd_pic)

    p = sub.add_parser('crop', help='convert one cutout of a sheet')
    p.add_argument('palette')
    p.add_argument('sheet')
    p.add_argument('out')
    p.add_argument('bg', help='background screen the cutout will land on')
    for a in ('x', 'y', 'w', 'h', 'dx', 'dy'):
        p.add_argument(a, type=int)
    p.set_defaults(func=cmd_crop)

    p = sub.add_parser('atlas', help="cutouts of one screen in a single image")
    p.add_argument('palette')
    p.add_argument('sheets', help='directory holding HOLH.BMP, MAINH.BMP, PRONUNH.BMP')
    p.add_argument('out')
    p.add_argument('--which', choices=('hol', 'pron'), default='hol')
    p.set_defaults(func=cmd_atlas)

    p = sub.add_parser('drill', help='drill screens, per category')
    p.add_argument('palette')
    p.add_argument('sheets', help='the FIN_IMS2 directory with the category folders')
    p.add_argument('outdir')
    p.set_defaults(func=cmd_drill)

    p = sub.add_parser('mainovl', help='lit panels of the main menu')
    p.add_argument('palette')
    p.add_argument('sheets')
    p.add_argument('outdir')
    p.set_defaults(func=cmd_mainovl)

    p = sub.add_parser('item', help="the picture of an entry, colours 16-31")
    p.add_argument('src')
    p.add_argument('out')
    p.add_argument('--width', type=int, default=118)
    p.add_argument('--height', type=int, default=78)
    p.add_argument('--base', type=int, default=16)
    p.add_argument('--colors', type=int, default=16)
    p.add_argument('--reserve', action='append', help='index=RGB not to be used')
    p.add_argument('--dither', choices=('none', 'fs'), default='none')
    p.set_defaults(func=cmd_item)

    args = ap.parse_args()
    args.func(args)


if __name__ == '__main__':
    main()
