#!/usr/bin/env python3
"""Build a proportional font for the CDTV out of a TrueType font.

  mkfont.py FONT.ttf SIZE OUT.h [--preview PNG]

The 1.3 ROM only has topaz 8, which is eight pixels wide per character: nine
characters fit across a panel of the HOL screen. Here the glyphs are drawn
without antialiasing at the requested size and each keeps only the width it
needs, so at the same height the text takes up nearly half the space.

The result is a ready-made AmigaOS TextFont structure:

  tf_CharData  the glyphs side by side in one bitmap, tf_YSize tall
  tf_CharLoc   per character: bit position (high 16 bits) and width
  tf_CharSpace how far the cursor advances after the character
  tf_CharKern  shift before the character (always zero here)

The last entry of the tables is the fallback character, used for codes the
font does not have.
"""
import argparse

from PIL import Image, ImageDraw, ImageFont

LO_CHAR, HI_CHAR = 32, 126
PAD = 4			# margin of the sheet the glyph is drawn on
GAP = 1			# pixels between one character and the next


def render(font, ch, box):
    """Draw one character with its baseline on row PAD + ascent."""
    im = Image.new('1', box, 0)
    d = ImageDraw.Draw(im)
    d.fontmode = '1'		# no antialiasing: the CDTV has a single colour
    d.text((PAD, PAD), ch, font=font, fill=1)
    return im


def glyphs(path, size, wordgap=1):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    box = (PAD * 2 + size * 2, PAD * 2 + ascent + descent)
    out = []
    top, bottom = box[1], 0
    for code in range(LO_CHAR, HI_CHAR + 1):
        ch = chr(code)
        im = render(font, ch, box)
        bbox = im.getbbox()
        advance = max(1, round(font.getlength(ch)))
        if ch == ' ':
            advance += wordgap	# the font's own space is a little tight
        if bbox is None:	# the space has no lit pixels
            out.append((None, 0, advance))
            continue
        x0, y0, x1, y1 = bbox
        top, bottom = min(top, y0), max(bottom, y1)
        out.append((im.crop((x0, 0, x1, box[1])), x1 - x0, advance))
    return out, top, bottom, PAD + ascent


def build(out, top, bottom, baseline):
    """Lay the glyphs side by side in one bitmap and prepare the tables."""
    height = bottom - top
    strip_w = sum(w for _, w, _ in out) + GAP
    strip = Image.new('1', (strip_w, height), 0)
    loc, space = [], []
    x = 0
    for im, w, advance in out:
        if im is not None:
            strip.paste(im.crop((0, top, w, bottom)), (x, 0))
        loc.append((x, w))
        space.append(advance)
        x += w
    loc.append((x, GAP))	# fallback character: one empty column
    space.append(GAP)
    return strip, loc, space, baseline - top


def rows(strip):
    """The bitmap row by row, in bytes (rows are aligned to 16 bits)."""
    modulo = ((strip.width + 15) // 16) * 2
    px = strip.load()
    data = []
    for y in range(strip.height):
        row = bytearray(modulo)
        for x in range(strip.width):
            if px[x, y]:
                row[x >> 3] |= 0x80 >> (x & 7)
        data.append(bytes(row))
    return data, modulo


def write_header(path, strip, loc, space, baseline, name):
    data, modulo = rows(strip)
    xsize = round(sum(space) / len(space))
    lines = ['/* generated by tools/mkfont.py: do not edit */',
             '#ifndef KLL_FONT_H', '#define KLL_FONT_H', '',
             f'/* {name}: {len(space) - 1} characters, {strip.width} pixels in all */',
             f'#define FONT_YSIZE\t{strip.height}',
             f'#define FONT_BASELINE\t{baseline}',
             f'#define FONT_XSIZE\t{xsize}',
             f'#define FONT_LOCHAR\t{LO_CHAR}',
             f'#define FONT_HICHAR\t{HI_CHAR}',
             f'#define FONT_MODULO\t{modulo}',
             f'#define FONT_BYTES\t{modulo * strip.height}', '',
             'static const UBYTE font_data[FONT_BYTES] = {']
    for y, row in enumerate(data):
        cells = ', '.join(f'0x{b:02X}' for b in row)
        lines.append(f'\t{cells},')
    lines += ['};', '',
              '/* bit position (high 16 bits) and width of every character */',
              'static const ULONG font_loc[] = {']
    for x, w in loc:
        lines.append(f'\t0x{(x << 16) | w:08X},')
    lines += ['};', '', 'static const UWORD font_space[] = {']
    lines.append('\t' + ', '.join(str(s) for s in space) + ',')
    lines += ['};', '', 'static const WORD font_kern[] = {']
    lines.append('\t' + ', '.join('0' for _ in space) + ',')
    lines += ['};', '', '#endif']
    with open(path, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'{path}: {strip.width}x{strip.height}, {modulo * strip.height} bytes of glyphs,'
          f' average width {xsize}')


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('font')
    ap.add_argument('size', type=int)
    ap.add_argument('out')
    ap.add_argument('--wordgap', type=int, default=1,
                    help='pixels to add to the space between words')
    ap.add_argument('--preview', help='PNG proof sheet with a sample line')
    args = ap.parse_args()

    out, top, bottom, baseline = glyphs(args.font, args.size, args.wordgap)
    strip, loc, space, base = build(out, top, bottom, baseline)
    write_header(args.out, strip, loc, space, base, f'{args.font} {args.size}')
    if args.preview:
        strip.convert('RGB').resize((strip.width * 3, strip.height * 3),
                                    Image.Resampling.NEAREST).save(args.preview)


if __name__ == '__main__':
    main()
